### ISSUE TITLE
Manage empty path

### ISSUE THREAD

**Issue by nlepage** [Zenika/immutadot#150]
### Description
Calling an immutadot function with an empty path throws an error.

**Version :** 1.0.0

#### Expected behavior
Not to crash with maximum call stack size exceeded...
Do nothing ? Crash with a better error message ?

#### Actual behavior
```
    RangeError: Maximum call stack size exceeded
      
      at walkPath (packages/immutadot/src/core/apply.js:95:41)
      at walkPath (packages/immutadot/src/core/apply.js:122:11)
      at walkPath (packages/immutadot/src/core/apply.js:122:11)
      at walkPath (packages/immutadot/src/core/apply.js:122:11)
...
```

**Comment by nlepage** [comment]
fixed by #154
